/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FindStationDialog: typeof import('./src/components/home/FindStationDialog.vue')['default']
    HeaderComponent: typeof import('./src/components/HeaderComponent.vue')['default']
    LineOptions: typeof import('./src/components/template/RoutesPage/LineOptions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StationOptions: typeof import('./src/components/template/RoutesPage/StationOptions.vue')['default']
    TitleSection: typeof import('./src/components/template/TitleSection.vue')['default']
  }
}
